<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1108" started-at="2017-07-17T14:59:07Z" finished-at="2017-07-17T14:59:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1108" started-at="2017-07-17T14:59:07Z" finished-at="2017-07-17T14:59:08Z">
      <class name="Tests.Login.LoginTest">
        <test-method status="PASS" signature="Initializer()[pri:0, instance:Tests.Login.LoginTest@13805618]" name="Initializer" is-config="true" duration-ms="959" started-at="2017-07-17T20:29:07Z" finished-at="2017-07-17T20:29:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initializer -->
        <test-method status="FAIL" signature="TestA_user_invalid_login_check()[pri:0, instance:Tests.Login.LoginTest@13805618]" name="TestA_user_invalid_login_check" duration-ms="11" started-at="2017-07-17T20:29:08Z" finished-at="2017-07-17T20:29:08Z">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[resource/login_test/Excel_Files/urls.xlsx (No such file or directory)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: resource/login_test/Excel_Files/urls.xlsx (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at Readers.XlsxReader.readit(XlsxReader.java:42)
	at utility.Datadecider.readit(Datadecider.java:30)
	at Tests.Login.LoginTest.TestA_user_invalid_login_check(LoginTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestA_user_invalid_login_check -->
        <test-method status="SKIP" signature="TestB_user_login_check()[pri:0, instance:Tests.Login.LoginTest@13805618]" name="TestB_user_login_check" duration-ms="0" started-at="2017-07-17T20:29:08Z" depends-on-methods="Tests.Login.LoginTest.TestA_user_invalid_login_check" finished-at="2017-07-17T20:29:08Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LoginTest.TestB_user_login_check()[pri:0, instance:Tests.Login.LoginTest@13805618] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LoginTest.TestB_user_login_check()[pri:0, instance:Tests.Login.LoginTest@13805618] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestB_user_login_check -->
        <test-method status="SKIP" signature="TestC_user_logout_check()[pri:0, instance:Tests.Login.LoginTest@13805618]" name="TestC_user_logout_check" duration-ms="0" started-at="2017-07-17T20:29:08Z" depends-on-methods="Tests.Login.LoginTest.TestB_user_login_check" finished-at="2017-07-17T20:29:08Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LoginTest.TestC_user_logout_check()[pri:0, instance:Tests.Login.LoginTest@13805618] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LoginTest.TestC_user_logout_check()[pri:0, instance:Tests.Login.LoginTest@13805618] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestC_user_logout_check -->
        <test-method status="PASS" signature="Closer()[pri:0, instance:Tests.Login.LoginTest@13805618]" name="Closer" is-config="true" duration-ms="119" started-at="2017-07-17T20:29:08Z" finished-at="2017-07-17T20:29:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Closer -->
      </class> <!-- Tests.Login.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
